# Chat API Contract for AI Chatbot
# OpenAPI 3.0 specification for MCP server chat endpoints

openapi: "3.0.3"
info:
  title: TaskFlow Chat API
  description: AI Chatbot API for natural language task management
  version: "1.0.0"
  contact:
    name: TaskFlow
    url: https://github.com/Psqasim/hackathon-todo

servers:
  - url: http://localhost:8001
    description: Local MCP server
  - url: https://mcp.taskflow.app
    description: Production MCP server (future)

paths:
  /api/chat:
    post:
      summary: Send message to AI agent
      description: |
        Sends a user message to the AI agent and streams the response.
        The agent may call MCP tools to perform task operations.
      operationId: sendChatMessage
      tags:
        - Chat
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatRequest"
            examples:
              createTask:
                summary: Create a task
                value:
                  message: "Add task to buy groceries tomorrow"
              listTasks:
                summary: List tasks
                value:
                  message: "Show my tasks"
              resumeConversation:
                summary: Continue conversation
                value:
                  message: "Make that high priority"
                  conversation_id: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: Successful response (streaming)
          content:
            text/event-stream:
              schema:
                $ref: "#/components/schemas/ChatStreamEvent"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: Rate limited (OpenAI API)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: Service unavailable (OpenAI or backend down)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/conversations:
    get:
      summary: List user's conversations
      description: Get all conversations for the authenticated user
      operationId: listConversations
      tags:
        - Conversations
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Maximum conversations to return
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Pagination offset
      responses:
        "200":
          description: List of conversations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationListResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/conversations/{conversation_id}:
    get:
      summary: Get conversation with messages
      description: Get a specific conversation and its message history
      operationId: getConversation
      tags:
        - Conversations
      security:
        - bearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Conversation with messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationDetailResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden - conversation belongs to another user
        "404":
          description: Conversation not found

    delete:
      summary: Delete conversation
      description: Delete a conversation and all its messages
      operationId: deleteConversation
      tags:
        - Conversations
      security:
        - bearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Conversation deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not found

  /health:
    get:
      summary: Health check
      description: Check if MCP server is running
      operationId: healthCheck
      tags:
        - Health
      responses:
        "200":
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  openai_configured:
                    type: boolean
                  backend_reachable:
                    type: boolean

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Phase II authentication

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          minLength: 1
          maxLength: 4000
          description: User's message to the AI agent
        conversation_id:
          type: string
          format: uuid
          description: Optional - resume existing conversation

    ChatStreamEvent:
      type: object
      description: Server-Sent Event for streaming response
      properties:
        event:
          type: string
          enum:
            - message_start
            - content_delta
            - tool_call
            - tool_result
            - message_end
            - error
        data:
          oneOf:
            - $ref: "#/components/schemas/MessageStartData"
            - $ref: "#/components/schemas/ContentDeltaData"
            - $ref: "#/components/schemas/ToolCallData"
            - $ref: "#/components/schemas/ToolResultData"
            - $ref: "#/components/schemas/MessageEndData"
            - $ref: "#/components/schemas/ErrorData"

    MessageStartData:
      type: object
      properties:
        conversation_id:
          type: string
          format: uuid
        message_id:
          type: string
          format: uuid

    ContentDeltaData:
      type: object
      properties:
        delta:
          type: string
          description: Chunk of response text

    ToolCallData:
      type: object
      properties:
        tool_name:
          type: string
        parameters:
          type: object

    ToolResultData:
      type: object
      properties:
        tool_name:
          type: string
        result:
          type: object
        success:
          type: boolean

    MessageEndData:
      type: object
      properties:
        full_content:
          type: string
        tool_calls_count:
          type: integer

    ErrorData:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    ConversationListResponse:
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: "#/components/schemas/ConversationSummary"
        total:
          type: integer

    ConversationSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        message_count:
          type: integer

    ConversationDetailResponse:
      type: object
      properties:
        conversation:
          $ref: "#/components/schemas/ConversationSummary"
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"

    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant, system]
        content:
          type: string
        tool_calls:
          type: array
          items:
            $ref: "#/components/schemas/ToolCall"
          nullable: true
        created_at:
          type: string
          format: date-time

    ToolCall:
      type: object
      properties:
        id:
          type: string
        tool_name:
          type: string
        parameters:
          type: object
        result:
          type: object
          nullable: true
        timestamp:
          type: string
          format: date-time

    DeleteResponse:
      type: object
      properties:
        deleted:
          type: boolean
        id:
          type: string
          format: uuid

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
          enum:
            - INVALID_REQUEST
            - UNAUTHORIZED
            - FORBIDDEN
            - NOT_FOUND
            - RATE_LIMITED
            - SERVICE_UNAVAILABLE
            - INTERNAL_ERROR
        details:
          type: object
          nullable: true

tags:
  - name: Chat
    description: AI chat endpoints
  - name: Conversations
    description: Conversation management
  - name: Health
    description: Service health checks
